src/Entity/Address.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AddressRepository")
 */
class Address
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nr_house;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nr_apartment;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip_code;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="address", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getNrHouse(): ?string
    {
        return $this->nr_house;
    }

    public function setNrHouse(string $nr_house): self
    {
        $this->nr_house = $nr_house;

        return $this;
    }

    public function getNrApartment(): ?string
    {
        return $this->nr_apartment;
    }

    public function setNrApartment(?string $nr_apartment): self
    {
        $this->nr_apartment = $nr_apartment;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Transaction.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TransactionRepository")
 */
class Transaction
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Bill", inversedBy="transactions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $bill;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $product_name;

    /**
     * @ORM\Column(type="float")
     */
    private $product_prise;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBill(): ?Bill
    {
        return $this->bill;
    }

    public function setBill(?Bill $bill): self
    {
        $this->bill = $bill;

        return $this;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(string $product_name): self
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getProductPrise(): ?string
    {
        return $this->product_prise;
    }

    public function setProductPrise(string $product_prise): self
    {
        $this->product_prise = $product_prise;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }
}

templates/components/alerts.html.twig
{% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="alert-{{ label }}">
            {{ message }}
        </div>
    {% endfor %}
    <hr>
{% endfor %}

templates/components/bill_view.html.twig
<div class="card text-center mt-3">
    <div class="card-header">
        {{bill.user.email}}, Status:
        {% if(bill.status == null) %}
            <span> unpaid</span>
        {% else %}
            <span> paid</span>
        {% endif %}
    </div>
    <div class="card-body">
        <h4 class="card-title">{{ bill.sum }} USD</h4>

        <!-- MODAL TRIGGER (PRODUCTS)-->
        <button
            class="btn btn-info btn-block mt-3"
            data-toggle="modal"
            data-target="#myModal_products{{bill.id}}"
        >
            Show Products
        </button>

        <!-- MODAL TRIGGER (ADDRESS)-->
        <button
            class="btn btn-info btn-block mt-3"
            data-toggle="modal"
            data-target="#myModal_address{{bill.id}}"
        >
            Show Address
        </button>
        {% if is_granted('ROLE_ADMIN') %}
            <a class="btn btn-secondary btn-block mt-3" href="/admin/paid/{{ bill.id }}">Enter Up Payment</a>
        {% endif %}
    </div>
    <div class="card-footer text-muted">
       {{ bill.time|date("H:m:s m/d/Y") }}
    </div>
</div>

<!-- MODAL (PRODUCTS) -->
<div class="modal" id="myModal_products{{bill.id}}">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title">Products:</h5>
        <button class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            {% for transaction in bill.transactions %}
                <hr>
                {% set prise = transaction.productPrise * transaction.quantity %}
                {{transaction.productName}} : {{transaction.productPrise}} USD x {{transaction.quantity}} = {{ prise }} USD
            {% endfor %}
        </div>
        <div class="modal-footer">
        <button class="btn btn-light" data-dismiss="modal">
            Close
        </button>
        </div>
    </div>
    </div>
</div>

<!-- MODAL (ADDRESS) -->
<div class="modal" id="myModal_address{{bill.id}}">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title">Address:</h5>
        <button class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            Address To Send:<br>
            {{ bill.user.address.street }} <br> 
            {{ bill.user.address.nrHouse }}
            {% if(bill.user.address.nrApartment != null) %}
                /{{ bill.user.address.nrApartment }} 
            {% endif %}
            <br>
            {{ bill.user.address.city }} <br>
            {{ bill.user.address.zipCode }} <br>
        </div>
        <div class="modal-footer">
        <button class="btn btn-light" data-dismiss="modal">
            Close
        </button>
        </div>
    </div>
    </div>
</div>

templates/components/cart_view.html.twig
{% set cart = app.session.get('cart') %}
{% if(cart != null) %}
    <ul class="list-group mt-3 mr-3">
        <li class="list-group-item list-group-item-light d-flex justify-content-between align-items-center text-primary">
            Shopping Cart
            <span class="badge badge-primary badge-pill">{{ cart|length }}</span>
        </li>
    </ul>
{% else %}
    <ul class="list-group mt-3 mr-3">
        <li class="list-group-item list-group-item-light d-flex justify-content-between align-items-center text-primary">
            Your Shopping Cart Is Empty
            <span class="badge badge-primary badge-pill">0</span>
        </li>
    </ul>
{% endif %}

templates/components/navbar.html.twig
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="/">MySymfonyShop</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"><span class="navbar-toggler-icon"></span></button>
        <div id="navbarNav" class="collapse navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about_us">Abous Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/products">Products</a>
                </li>
            </ul>
            
            <ul class="navbar-nav ml-auto">
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('user_dashboard') }}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_login') }}">Login</a>
                    </li>
                {% endif %}
                {% if is_granted('ROLE_ADMIN') %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/dashboard">ADMIN</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>